language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
  - build-tools-27.0.3
  - android-27

before_install:
  - yes | sdkmanager "platforms;android-27"

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - openssl aes-256-cbc -d -k "$SECRET_FILES_KEY" -in release.jks.enc -out release.jks
  - openssl aes-256-cbc -d -k "$SECRET_FILES_KEY" -in keys.json.enc -out keys.json

script:
  - ./gradlew clean build assembleRelease

after_success:
  - ./gradlew publishApkRelease